version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password  
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"    
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka-broker
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9092
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      "9092:9092"
    depends_on:
      - postgres

  java_etl:
    build: ./java-etl
    container_name: java-etl
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/etl_db
      DB_USER: etl_user
      DB_PASSWORD: etl_password
    depends_on:
      - postgres

  python_etl:
    build: ./python-etl
    container_name: python-etl
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: etl_db
      DB_USER: etl_user
      DB_PASSWORD: etl_password
    depends_on:
      - postgres

  kafka-etl:
    build: ./kafka-etl
    container_name: kafka-etl
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: etl_db
      DB_USER: etl_user
      DB_PASSWORD: etl_password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: etl-KAFKA_TOPIC
    depends_on:
      - postgres
      - kafka

volumes:
  pgdata: